ALTER TABLE node_overviews ADD COLUMN familiarity_level TEXT NOT NULL DEFAULT 'UNASSESSED'
  CHECK (familiarity_level IN ('UNASSESSED','TARGET','VERY_FAMILIAR','BASICALLY_KNOW','HEARD_OF','DONT_KNOW'));
