"""Rebuild checked-in, disjoint WOFF2 subsets without changing glyph outlines."""
from hashlib import sha256
from io import BytesIO
from pathlib import Path
import json
from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "scripts/font-sources/SourceHanSansCN-VF.woff2"
OUT = ROOT / "public/fonts/han"
SOURCE_BYTES = SOURCE.read_bytes()
original = TTFont(BytesIO(SOURCE_BYTES))
available = {cp for cp in original.getBestCmap() if cp > 0x024F}

# Fixed application copy is loaded in one small file. Dynamic text uses additional
# common-character and rare-character shards, without requiring a full-font fallback.
ui = set()
for path in (ROOT / "src").rglob("*"):
    if path.suffix in {".ts", ".tsx"}:
        ui.update(ord(char) for char in path.read_text(encoding="utf-8"))
ui &= available
common = set()
for high in range(0xB0, 0xD8):
    for low in range(0xA1, 0xFF):
        try:
            common.add(ord(bytes([high, low]).decode("gb2312")))
        except UnicodeDecodeError:
            pass
common = (common & available) - ui
rare = available - ui - common

groups = [("ui", sorted(ui))]
for label, codepoints, size in [("common", common, 256), ("rare", rare, 512)]:
    ordered = sorted(codepoints)
    groups.extend((f"{label}-{offset // size:03}", ordered[offset:offset + size]) for offset in range(0, len(ordered), size))

def unicode_ranges(points):
    ranges = []
    start = previous = points[0]
    for point in points[1:]:
        if point == previous + 1:
            previous = point
            continue
        ranges.append(f"U+{start:X}" if start == previous else f"U+{start:X}-{previous:X}")
        start = previous = point
    ranges.append(f"U+{start:X}" if start == previous else f"U+{start:X}-{previous:X}")
    return ",".join(ranges)

OUT.mkdir(parents=True, exist_ok=True)
manifest = {"sourceSha256": sha256(SOURCE_BYTES).hexdigest(), "family": "KnowledgeSteps Han SC", "files": []}
css = ["/* Generated by scripts/subset-han-font.py; retain SourceHanSans-LICENSE.txt. */"]
covered = set()
for label, points in groups:
    font = TTFont(BytesIO(SOURCE_BYTES), recalcTimestamp=False)
    options = subset.Options()
    options.name_IDs = ["*"]
    options.name_legacy = True
    options.name_languages = ["*"]
    options.layout_features = ["*"]
    reducer = subset.Subsetter(options=options)
    reducer.populate(unicodes=points)
    reducer.subset(font)
    # OFL reserves the name "Source": give derived subsets their own font name.
    for record in font["name"].names:
        if record.nameID in {0, 7, 8, 9, 10, 11, 12, 13, 14}:
            continue  # Preserve original copyright, manufacturer and license text.
        value = record.toUnicode().replace("Source Han Sans", "KnowledgeSteps Han").replace("SourceHanSans", "KnowledgeStepsHan")
        if record.nameID in {1, 16}:
            value = "KnowledgeSteps Han SC"
        record.string = value.encode(record.getEncoding())
    buffer = BytesIO()
    font.flavor = "woff2"
    font.save(buffer)
    data = buffer.getvalue()
    digest = sha256(data).hexdigest()
    filename = f"ks-han-{label}-{digest[:12]}.woff2"
    (OUT / filename).write_bytes(data)
    restored = TTFont(BytesIO(data))
    assert set(restored.getBestCmap()) == set(points), f"Coverage mismatch: {label}"
    assert not covered.intersection(points), "Overlapping unicode ranges"
    covered.update(points)
    assert "fvar" in restored, "Variable weight axis was lost"
    ranges = unicode_ranges(points)
    manifest["files"].append({"file": f"han/{filename}", "sha256": digest, "bytes": len(data), "characters": len(points), "unicodeRange": ranges})
    css.append(f'''@font-face {{
  font-family: "KnowledgeSteps Han SC";
  src: url("/fonts/han/{filename}") format("woff2");
  font-weight: 100 900;
  font-style: normal;
  font-display: swap;
  unicode-range: {ranges};
}}''')
    print(f"{label}: {len(points)} characters, {len(data)} bytes", flush=True)

assert covered == available, "A character from the original font lost its fallback"
(ROOT / "src/design/han-subsets.css").write_text("\n\n".join(css) + "\n", encoding="utf-8")
(ROOT / "scripts/han-subsets.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
live = {Path(item["file"]).name for item in manifest["files"]}
for stale in OUT.glob("ks-han-*.woff2"):
    if stale.name not in live and stale.resolve().parent == OUT.resolve():
        stale.unlink()
print(f"Validated {len(groups)} files covering {len(covered)} characters; original font is not served.", flush=True)
